name: build-offline-docs

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #  paths-ignore:
  #  - ".github/**"
  #  - "README.md"
  #pull_request:
  #  branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: sudo apt install -y weasyprint 
      - run: pip install mkdocs-material mkdocs-pandoc-plugin mkdocs-to-pdf mkdocs-print-site-plugin htmlark[http,parsers]
      
      # Build full site
      - run: |
          export ENABLED_PRINT_SITE=false 
          mkdocs build
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site/
      
      # Build full site with single html and pdf
      - run: |
          export ENABLED_PRINT_SITE=true
          export ENABLE_PDF_EXPORT=1
          sed -i -e 's/- navigation.indexes/#- navigation.indexes/' -e 's/- toc.integrate/#- toc.integrate/' mkdocs.yml
          mkdocs build -d site-html
          cd site-html
          htmlark print_page.html -o standalone.html
      - uses: actions/upload-artifact@v4
        with:
          name: doc-html
          path: site-html/standalone.*
